api/urls.py
from django.urls import path, re_path
from api import views as api_views
import api

app_name = 'api'

urlpatterns = [
    path('refs/', api_views.ref_api, name='ref_api'),
    path('widget/', api_views.widget, name='widget tracking'),
    path('links/', api_views.links_generated, name='links generated'),
    re_path(r'^postback/$', api_views.involveAsia, name='postbackURL')
]

webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from users.sitemaps import PartnerSiteMap
from django.contrib.sitemaps.views import sitemap
from django.views.generic.base import TemplateView

sitemaps = {
    'Partner': PartnerSiteMap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_views.home, name='home'),
    path('ref/<str:ref_code>/', user_views.refSignUp, name="referral sign up"),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', user_views.login, name = "login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('brands/', user_views.brands, name = 'brands'),
    path('IntlBrands/', user_views.intlBrands, name = 'IntlBrands'),
    path('referral/', include('referrals.urls')),
    path('api/', include('api.urls')),
    path('merchants/', include('merchants.urls')),
    path("robots.txt",TemplateView.as_view(template_name="users/robots.txt", content_type="text/plain")),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from referrals.models import OrphanList, orphanReceipt, receipts
from django.db.models.signals import post_save
from django.dispatch import receiver

User._meta.get_field('email')._unique = True

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=CASCADE)
    Phone_Number = PhoneNumberField(blank=False, unique=True)
    wallet= models.DecimalField(max_digits=6, decimal_places=2, default=0)
    num_of_refers = models.IntegerField(default=0)
    links_created = models.IntegerField(default=0)
    signup_refs = models.IntegerField(default=0)
    code = models.CharField(max_length=30, blank= True)
    recommended_by = models.ForeignKey(User, on_delete=CASCADE, blank=True, related_name="ref_by", null=True)

    def __str__(self):
        return f"{self.user.username}'s profile"

@receiver(post_save, sender = Profile)
def post_save_profile(sender, instance, created, *args, **kwargs):
    if created:
        #check orphans for partner orders
        if OrphanList.objects.filter(refereeEmail = instance.user.email).exists():
            # update the username in the ref object
            ref_obj = OrphanList.objects.get(refereeEmail = instance.user.email).referral_obj
            ref_obj.referee_username = instance.user.username
            ref_obj.referee_has_account = True
            
            #update the wallet and num refers of referee
            referee = User.objects.get(username = ref_obj.referee_username)
            referee.profile.wallet = referee.profile.wallet + ref_obj.referee_cashback
            referee.profile.num_of_refers = referee.profile.num_of_refers + 1
            referee.profile.save()

            ref_obj.save()
         
            #delete the orphan list object
            obj = OrphanList.objects.get(refereeEmail = instance.user.email)
            obj.delete()
        
        #check orphan receipts for amazon order
        if orphanReceipt.objects.filter(referee = instance.Phone_Number).exists():
            #update username of referee on receipt object
            receipt_obj = orphanReceipt.objects.get(referee = str(instance.Phone_Number)).referral_obj
            receipt_obj.referee = instance.user.username
            print(receipt_obj.referee )
            receipt_obj.save()

            #update the number of refers of referee
            referee = User.objects.get(username = receipt_obj.referer)
            referee.profile.num_of_refers = referee.profile.num_of_refers + 1
            referee.profile.save()

            obj = orphanReceipt.objects.get(referee = str(instance.Phone_Number))
            obj.delete()

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import widgets
from .models import Profile
from phonenumber_field.modelfields import PhoneNumberField

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email' , 'class': 'inputs'}))
    password1 = forms.CharField(max_length=16, widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'inputs'}))
    password2 = forms.CharField(max_length=16, widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password', 'class': 'inputs'}))
    class Meta:
        model = User
        fields = ['username','email','password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username', 'class': 'inputs'}),
        }

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']

class PhoneForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['Phone_Number']
        widgets = {
            'Phone_Number': forms.TextInput(attrs={'placeholder': 'Phone Number', 'class': 'inputs'})
        }

users/views.py
import decimal
from email import message
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.messages import constants
from django.contrib.auth import authenticate, login
from merchants.models import Amazon_Brand, Partner_Merchant
from .forms import UserUpdateForm, UserRegisterForm, PhoneForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from webapp import settings

def home(request):
    context = {
        'amazon': Amazon_Brand.objects.all(),
        'partner': Partner_Merchant.objects.all()
    }
    return render(request, 'users/home.html', context)

def refSignUp(request, *args, **kwargs):
    code = str(kwargs.get('ref_code'))
    if User.objects.filter(username = code).exists():
        return registerWCode(request, code)
    else:
        return render(request, 'users/home.html', {})


def intlBrands(request):
    context = {
        'amazon': Amazon_Brand.objects.all(),
        'partner': Partner_Merchant.objects.all()
    }
    return render(request, 'users/IntlBrands.html', context)

def brands(request):
    context = {
        'amazon': Amazon_Brand.objects.all(),
        'partner': Partner_Merchant.objects.all()
    }
    return render(request, 'users/brands.html', context)

@login_required
def profile(request):
    user = User.objects.get(pk=request.user.pk)
    if request.method=="POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        if u_form.is_valid():
            u_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('/profile')
    else:
        u_form = UserUpdateForm(instance=request.user)


    context = {
        'user': user,
        'u_form': u_form,
    }

    return render(request, 'users/profile.html', context)

def registerWCode(request, code):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        p_reg_form = PhoneForm(request.POST)
        if form.is_valid() and p_reg_form.is_valid():
            user = form.save()
            #user.refresh_from_db()  # load the profile instance created by the signal
            p_reg_form = p_reg_form.save(commit=False)
            p_reg_form.user = user
            referer = User.objects.get(username = code)
            p_reg_form.code = user.username
            p_reg_form.recommended_by = referer
            p_reg_form.wallet = p_reg_form.wallet + round(decimal.Decimal(5),2)
            p_reg_form.save()

            referer.profile.signup_refs = referer.profile.signup_refs + 1
            referer.profile.wallet = referer.profile.wallet + round(decimal.Decimal(5),2)
            referer.profile.save()
            username = user.username      


            messages.add_message(request, constants.SUCCESS, f"Account created for '{username}'.")
            new_user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'],
            )

            subject = 'Thank you for signing up!'
            html_message = render_to_string('users/followers.html')
            plain_message = strip_tags(html_message)
            from_email = settings.EMAIL_HOST_USER
            to = user.email
            mail.send_mail(subject, plain_message, from_email,[to], html_message = html_message)

            subject = 'Thank you for Referring!'
            html_message = render_to_string('users/influencer.html', {'user': referer})
            plain_message = strip_tags(html_message)
            from_email = settings.EMAIL_HOST_USER
            to = referer.email
            mail.send_mail(subject, plain_message, from_email,[to], html_message = html_message)

            login(request, new_user)
            return redirect('brands')
    else:
        form = UserRegisterForm()
        p_reg_form = PhoneForm()
    context = {
        'form': form,
        'p_reg_form': p_reg_form
    }
    return render(request, 'users/register.html', context)

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        p_reg_form = PhoneForm(request.POST)
        if form.is_valid() and p_reg_form.is_valid():
            user = form.save()
            #user.refresh_from_db()  # load the profile instance created by the signal
            p_reg_form = p_reg_form.save(commit=False)
            p_reg_form.user = user
            p_reg_form.save()

            username = user.username      
            messages.add_message(request, constants.SUCCESS, f"Account created for '{username}'.")
            new_user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'],
            )

            subject = 'Thank you for signing up!'
            html_message = render_to_string('users/register_email.html', {'username': username})
            plain_message = strip_tags(html_message)
            from_email = settings.EMAIL_HOST_USER
            to = user.email
            mail.send_mail(subject, plain_message, from_email,[to], html_message = html_message)

            login(request, new_user)
            return redirect('brands')
    else:
        form = UserRegisterForm()
        p_reg_form = PhoneForm()
    context = {
        'form': form,
        'p_reg_form': p_reg_form
    }
    return render(request, 'users/register.html', context)

def login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        message.add_message(request, constants.SUCCESS, f'Successfully logged in.')
        return redirect('/brands/')
    else:
        print("error loading in")
    return render(request, 'users/login.html', {})
    

users/templates/users/base.html
{% load tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    {% block extra_meta %}{% endblock %}
    {% tailwind_css %}
    <title>{% block title %} {% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet"> 
    <link rel="shortcut icon" href="{% static 'users/img/pageAssets/m-logo.png' %}" type="image/x-icon">
    {% block extra_head %} {% endblock %}
</head>

<body class="font-DMsans tracking-wide scroll-smooth">
    <nav class="navbar flex items-start flex-col md:flex-row md:justify-between md:items-center text-black py-4  border-b-2">
      <div class="brand-title text-3xl flex px-3 sm:px-5">
        <img src="{% static 'users/img/pageAssets/m-logo.png' %}" alt="logo of moneymoves">
        <a class="font-bold text-2xl sm:text-xl px-3 pt-2" href="/">
          Money<span class="text-primary">Moves</span>
        </a> 
      </div>

      <a href="#" class="toggle-button">
        <div class="
          burgerbuns
          flex
          flex-col
          justify-center 
          items-center 
          sm:w-6
          sm:h-7
          w-5 
          h-6 
          cursor-pointer 
          transition-all 
          duration-500 
          "
        >
          <div class="burger"></div>
        </div>
      </a>

      <div class="">
        <ul class="navbar-links m-0 mt-4 hidden md:mt-0 md:flex list-none fixed md:static w-full h-full">
          <div id="navbar-wrapper" class="flex flex-col md:flex-row justify-center items-center mt-5 md:mt-0">
            <li><a class="block p-2 hover:text-gray-600" href="/brands/">Brands</a></li>
            {% if user.is_authenticated %}
            <li><a class="block p-2 hover:text-gray-600" href="/referrals/">Wallet</a></li>
            <li><a class="block p-2 hover:text-gray-600" href="/profile/">Profile</a></li>
            {% else %}
            {% block navlink %}{% endblock %}
            <li><a class="block p-2 hover:text-gray-600" href="https://moves.money/merchant">For Merchants</a></li>
            {% endif %}
            {% if user.is_authenticated %}
            <li>          
              <a class="block pt-1" href="/logout/">
                <button class="px-3 py-1 bg-gray-700 text-white rounded-2xl">
                  Logout
                </button>
              </a>  
            </li>
            {% else %}
            <li><a class="block p-2 sm:pl-4 hover:text-gray-600" href="/login/">Login</a></li>
            <li>          
              <a class="block" href="/register/">
                <button class="px-3 py-1 bg-primary hover:bg-blue-500 text-white rounded-2xl">
                  Sign Up
                </button>
              </a>  
            </li>
            {% endif %}
          </div>
        </ul>
      </div>
    </nav>
    
    {% block content %}
    {% endblock %}
    
  <footer class="text-center lg:text-left bg-gray-100 text-gray-600">
    <div class="mx-6 py-10 text-center md:text-left border-t-2 px-7 sm:px-12 md:px-20 lg:px-28">
      <div class="grid grid-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
        <div class="">
          <h6 class="
              uppercase
              font-semibold
              mb-4
              flex
              items-center
              justify-center
              md:justify-start
            ">
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="cubes"
              class="w-4 mr-3" role="img" xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 512 512">
              <path fill="currentColor"
                d="M488.6 250.2L392 214V105.5c0-15-9.3-28.4-23.4-33.7l-100-37.5c-8.1-3.1-17.1-3.1-25.3 0l-100 37.5c-14.1 5.3-23.4 18.7-23.4 33.7V214l-96.6 36.2C9.3 255.5 0 268.9 0 283.9V394c0 13.6 7.7 26.1 19.9 32.2l100 50c10.1 5.1 22.1 5.1 32.2 0l103.9-52 103.9 52c10.1 5.1 22.1 5.1 32.2 0l100-50c12.2-6.1 19.9-18.6 19.9-32.2V283.9c0-15-9.3-28.4-23.4-33.7zM358 214.8l-85 31.9v-68.2l85-37v73.3zM154 104.1l102-38.2 102 38.2v.6l-102 41.4-102-41.4v-.6zm84 291.1l-85 42.5v-79.1l85-38.8v75.4zm0-112l-102 41.4-102-41.4v-.6l102-38.2 102 38.2v.6zm240 112l-85 42.5v-79.1l85-38.8v75.4zm0-112l-102 41.4-102-41.4v-.6l102-38.2 102 38.2v.6z">
              </path>
            </svg>
            Need help?
          </h6>
          <p>Send us an email at
            <a href="mailto:support@moves.money">support@moves.money</a>
          </p>
        </div>
        <div class="">
          <h6 class="uppercase font-semibold mb-4 flex justify-center md:justify-start">
            links
          </h6>
          <p class="mb-4">
            <a href="#" class="text-gray-600">For Merchants</a>
          </p>
          <p class="mb-4">
            <a href="https://rainy-mint-11d.notion.site/MoneyMoves-FAQ-00239b8983544167b533490fdddcdf8e" class="text-gray-600">FAQs</a>
          </p>
        </div>
        <div class="">
          <h6 class="uppercase font-semibold mb-4 flex justify-center md:justify-start">
            Get connected
          </h6>
          <p class="flex items-center justify-center md:justify-start mb-4">
            <svg aria-hidden="true" focusable="false" data-prefix="fab" data-icon="instagram"
                  class="w-4 mr-4" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                <path fill="currentColor"
                d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z">
                </path>
            </svg>
            <a href="https://www.instagram.com/get.moneymoves/">@get.money_moves</a>
          </p>

          <p class="flex items-center justify-center md:justify-start mb-4">
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="envelope"
              class="w-4 mr-4" role="img" xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 512 512">
              <path fill="currentColor"
                d="M502.3 190.8c3.9-3.1 9.7-.2 9.7 4.7V400c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V195.6c0-5 5.7-7.8 9.7-4.7 22.4 17.4 52.1 39.5 154.1 113.6 21.1 15.4 56.7 47.8 92.2 47.6 35.7.3 72-32.8 92.3-47.6 102-74.1 131.6-96.3 154-113.7zM256 320c23.2.4 56.6-29.2 73.4-41.4 132.7-96.3 142.8-104.7 173.4-128.7 5.8-4.5 9.2-11.5 9.2-18.9v-19c0-26.5-21.5-48-48-48H48C21.5 64 0 85.5 0 112v19c0 7.4 3.4 14.3 9.2 18.9 30.6 23.9 40.7 32.4 173.4 128.7 16.8 12.2 50.2 41.8 73.4 41.4z">
              </path>
            </svg>
            <a href="mailto:hello@moves.money">hello@moves.money</a>
          </p>
          <p class="flex items-center justify-center md:justify-start mb-4">
        </div>
      </div>
    </div>
    <div class="text-center p-6 bg-gray-200">
      <span>© 2021 Copyright</span>
      <a class="text-gray-600 font-semibold" href="/">MoneyMoves &#8482</a>
    </div>
  </footer>
  <script src="{% static 'users/js/base.js' %}"></script>
</body>
</html>

users/templates/users/influencer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome Email</title>
</head>

<style>
    .main-body{
        background-color: white;
        text-align: center;
        font-family: sans-serif;
        font-size: 2em;
        margin: 2em auto;
        max-width: 80%;
    }
    /* .container-one{
        justify-content: center;
        text-align: center;
        background-color:#E0E5F1;
        margin: 10%;
        padding-bottom: 20px;
        font-size: 14px;
    } */
    .container-main{
        justify-content: center;
        text-align: center;
        background-color: #E0E5F1;
        margin: 10%;
        padding-bottom: 20px;
        max-width: 80%;
        font-size: 14px;
    }

    .hr{
        border: 2px solid black;
        /* border-radius: 5px; */
        max-width: 80%;
    }

    .welcome-title{
        text-align: center;
        padding: 20px;
        font-family: sans-serif;
        font-size: 24px;
    }
    .footer{
        justify-content: center;
        text-align: center;
        background-color: #E0E5F1;
        margin: 10%;
        padding-bottom: 20px;
        font-size: 14px;

    }

    .button {
  background-color: black; /* Green */
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 10px ;
  cursor: pointer;
}

.p{
    padding:10px;
}
</style>


<body class="main-body">
    <div class="container-main">

    
    <div class="container-one">
        <h1 class="welcome-title">Hello from MoneyMoves 👋🏻</h1></header>
        <p> Helping Gen Z make their money move 😎 </p>
        <hr class="hr">


        <h2>Congrats! 🚀 </h2>
        <p class="p">You just earned <span style="color: green;">$5</span> from recommeding your friends to sign up for MoneyMoves! 🎉 </p>
        <p class="p"> You have {{user.profile.signup_refs}} with {{user.profile.wallet}} in your MoneyMoves wallet! 💰 </p>
        <p class="p">Thanks for sharing MoneyMoves with your friends and being a part of our journey to enable financial literacy through social commerce! ❤️ </p>
        <p class="p"><em> New sign ups will have to complete 3 successful referrals to be eligible! </em></p>
        
    </div>
    <div>
        <button class="button" onclick="location.href = 'https://moneymoves.app/';">View my earnings</button>
    </div>
</body>
<footer class='footer'>
    <!-- <img src="https://ik.imagekit.io/2bmvtzrfkar/Email_templates/MMLogo_V4Sbekfx3NW.png?updatedAt=1632866560822" style="height:1em, width: 1em; padding: 20px;">  -->
    <p> Reach out to us at hello@moves.money for any questions! </p>
    <a href="https://www.instagram.com/get.moneymoves/">
        <img src="https://ik.imagekit.io/2bmvtzrfkar/Email_templates/insta_UInoS_nLv.png" alt="instagram icon">
    </a>
    <p> Made with ❤️</p>
</footer>
</div>
</html>

users/templates/users/login.html
{% load tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="MoneyMoves is a fintech company that helps users grow their cashback earned through our platform.">
    {% tailwind_css %}
    <title>Login | MoneyMoves</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet"> 
    <link rel="shortcut icon" href="{% static 'users/img/pageAssets/m-logo.png' %}" type="image/x-icon">
</head>
<body class="font-DMsans">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <h1>{{ message }}</h1>
        
        {% endfor %}
    </ul>
{% endif %}
    <main>
        <div class="brand-title text-3xl flex px-3 sm:px-5 mt-5">
            <img src="{% static 'users/img/pageAssets/m-logo.png' %}" alt="logo of moneymoves">
            <a class="font-bold text-2xl sm:text-xl px-3 pt-3" href="/">
              Money<span class="text-primary">Moves</span>
            </a> 
        </div>
        <section class="py-20 px-12 sm:px-16 md:px-20 lg:px-28">
            <h1 class="text-2xl sm:text-6xl text-center font-bold">Log in to Money<span class="text-primary"> Moves</span></h1>
            <h2 class="text-md sm:text-2xl text-center my-5">Don't compromise your lifestyle to start investing and earning.</h2>
            <div>
                <form method="POST" class="flex flex-col justify-center items-center">
                    {% csrf_token %}
                    <input type="username" for="username" placeholder="Username">
                    <input type="password" for="password" placeholder="Password">
                    <button class="my-5 sm:mt-10 px-6 py-1 sm:px-3 sm:py-1 text-lg bg-primary hover:bg-blue-500 hover:scale-105 text-white rounded-lg">
                        Confirm
                    </button>
                </form>
                <div>
                    <small>
                        Already have an account? <a href="{% url 'login' %}"> <span class="text-blue-500 hover:text-blue-300">Sign In.</span></a>
                    </small>
                </div>
            </div>
        </section>
    </main>

    <footer class="bg-bg2 py-10 px-12 sm:px-16 md:px-20 lg:px-28">
        <h1 class="text-lg">Feel free to send us an email if you have any questions</h1>
        <a href="mailto:hello@moves.money" class="text-sm mt-5">hello@moves.money</a>
    </footer>
</body>
</html>

users/templates/users/logout.html
{% extends "users/base.html" %}
{% block title %}Log Out{% endblock %}
{% load static %}
{% block extra_head %}<link rel="stylesheet" type="text/css" href="{% static 'users/logout.css' %}">{% endblock %}
{% block content %}


<section class="logout-container">
    <h2 class="thanks">Thanks for visiting Money<span class="moves">Moves</span>! You have been logged out</h2>

    <div>
        <h5 class="outro">
            You can always 
            <a class="ml-2" href="{% url 'login' %}">Log In Again</a>
        </h5>
    </div>
</section>
    
{% endblock %}

users/templates/users/password_reset.html
{% extends "users/base.html" %}
{% block title %}Password Reset{% endblock %}
{% load static %}
{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'users/password_reset.css' %}">
{% endblock %}
{% block content %}

    <section class="login-container">
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">  <!-- singular -->
                <h4>{{ message }}</h4>
            </div>
            {% endfor %}
        {% endif %}   
        
        {{ form.errors }}
        
        <h1 class="heading">Reset Password</h1>
        <form method="POST">
            {% csrf_token %}
            <input type="email" name="email" id="email" placeholder="email" required-id="id_email">
            <br>
            <button type="submit">Request Password Reset</button>
        </form>
    </section>
{% endblock %}